#!/usr/bin/env bash
set -euo pipefail

NPROC_PER_NODE="${NPROC_PER_NODE:-8}"
TRAIN_SCRIPT="${TRAIN_SCRIPT:-train_gpt.py}"
TORCHRUN_ARGS="${TORCHRUN_ARGS:-}"

DATA_PATH="${DATA_PATH:-}"
HP_TRAIN_FILES="${HP_TRAIN_FILES:-}"
HP_VAL_FILES="${HP_VAL_FILES:-}"
HP_VAL_TOKENS="${HP_VAL_TOKENS:-}"
HP_TRAIN_BATCH_SIZE="${HP_TRAIN_BATCH_SIZE:-}"
HP_TRAIN_MAX_SEQ_LEN="${HP_TRAIN_MAX_SEQ_LEN:-}"
HP_VAL_BATCH_SIZE="${HP_VAL_BATCH_SIZE:-}"
HP_NUM_ITERATIONS="${HP_NUM_ITERATIONS:-}"
HP_COOLDOWN_FRAC="${HP_COOLDOWN_FRAC:-}"
HP_MIN_LR_MULT="${HP_MIN_LR_MULT:-}"
HP_ADAM_LR="${HP_ADAM_LR:-}"
HP_MUON_LR="${HP_MUON_LR:-}"
HP_RUN_ID="${HP_RUN_ID:-}"
HP_VAL_LOSS_EVERY="${HP_VAL_LOSS_EVERY:-}"
HP_VAL_LINEAR_EVAL_STEPS="${HP_VAL_LINEAR_EVAL_STEPS:-}"
HP_LOG_INTERVAL="${HP_LOG_INTERVAL:-}"
HP_HIST_INTERVAL="${HP_HIST_INTERVAL:-}"
HP_HIST_SAMPLE_SIZE="${HP_HIST_SAMPLE_SIZE:-}"
HP_LOGITS_SAMPLE_TOKENS="${HP_LOGITS_SAMPLE_TOKENS:-}"
HP_WANDB_PROJECT="${HP_WANDB_PROJECT:-}"
HP_SAVE_CHECKPOINT="${HP_SAVE_CHECKPOINT:-}"
HP_BLOCK_SIZE="${HP_BLOCK_SIZE:-}"
HP_WS_SCHEDULE="${HP_WS_SCHEDULE:-}"
HP_WS_VALIDATE="${HP_WS_VALIDATE:-}"
HP_DROPSOFTMAX_STEP="${HP_DROPSOFTMAX_STEP:-}"
HP_DROPSOFTMAX_MODE="${HP_DROPSOFTMAX_MODE:-}"
HP_LINEAR_ATTN_CHUNK_SIZE="${HP_LINEAR_ATTN_CHUNK_SIZE:-}"

export DATA_PATH
export HP_TRAIN_FILES
export HP_VAL_FILES
export HP_VAL_TOKENS
export HP_TRAIN_BATCH_SIZE
export HP_TRAIN_MAX_SEQ_LEN
export HP_VAL_BATCH_SIZE
export HP_NUM_ITERATIONS
export HP_COOLDOWN_FRAC
export HP_MIN_LR_MULT
export HP_ADAM_LR
export HP_MUON_LR
export HP_RUN_ID
export HP_VAL_LOSS_EVERY
export HP_VAL_LINEAR_EVAL_STEPS
export HP_LOG_INTERVAL
export HP_HIST_INTERVAL
export HP_HIST_SAMPLE_SIZE
export HP_LOGITS_SAMPLE_TOKENS
export HP_WANDB_PROJECT
export HP_SAVE_CHECKPOINT
export HP_BLOCK_SIZE
export HP_WS_SCHEDULE
export HP_WS_VALIDATE
export HP_DROPSOFTMAX_STEP
export HP_DROPSOFTMAX_MODE
export HP_LINEAR_ATTN_CHUNK_SIZE

torchrun --standalone --nproc_per_node="${NPROC_PER_NODE}" ${TORCHRUN_ARGS} "${TRAIN_SCRIPT}"
